name: Run Python Script

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"
  push:
    paths:
      - "script/main.py"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f script/requirements.txt ]; then pip install -r script/requirements.txt; fi

      - name: Run script
        run: python script/main.py

      - name: Commit and push if changed
        run: |
          git config --global user.email "github-action@jamelouis.com"
          git config --global user.name "Github Actions"
          git add public/
          git diff --quiet && git diff -staged --quiet || (git commit -m "Auto update public folder" && git push)
