name: Run Python Script

on:
  workflow_dispatch:
  schedule:
    - cron: "30 10 * * 1-5"
  push:
    paths:
      - "script/**"
      - ".github/workflows/run_script.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f script/requirements.txt ]; then pip install -r script/requirements.txt; fi

      - name: Run script
        env:
          API_KEY: ${{ secrets.SUPABASE}}
        run: python script/main.py

      - name: Commit and push if changed
        run: |
          git config --global user.email "github-action@jamelouis.com"
          git config --global user.name "Github Actions"
          git add public/
          git diff --quiet && git diff -staged --quiet || (git commit -m "Auto update public folder" && git push)
          
      - name: Send email on failure
        uses: kantakumari/custom-actions-2@v2.3
